# Lecture 2 - Pandas, subsetting and slicing

**Credits:**

Created by Sippo Rossi for the course Python Programming for Business Intelligence at Hanken.

___

This notebook demonstrates how you can select specific rows and columns from a Pandas dataframe.

In [2]:
import pandas as pd

In [46]:
# Loading the UCI Online Retail dataset into this Jupyter Notebook
# First download the dataset from the source: https://archive.ics.uci.edu/ml/datasets/Online+Retail
# Place the dataset in the same folder as this notebook (or specify the path below within "")
# This dataset contains transactional data from a UK-based online retailer (2010-2011).

df = pd.read_excel("Online Retail.xlsx")

In [6]:
# What the dataset looks like

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

## Using .loc

### Selecting rows and returning a Pandas series or DataFrame

In [7]:
# Single bracket returns a series

df.loc[1]

InvoiceNo                   536365
StockCode                    71053
Description    WHITE METAL LANTERN
Quantity                         6
InvoiceDate    2010-12-01 08:26:00
UnitPrice                     3.39
CustomerID                 17850.0
Country             United Kingdom
Name: 1, dtype: object

In [8]:
type(df.loc[1])

pandas.core.series.Series

In [9]:
# Double bracket returns a DataFrame

df.loc[[1]]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [10]:
type(df.loc[[1]])

pandas.core.frame.DataFrame

### Slicing

Slicing can be applied to rows or columns with df[a:b] where a is the start and b is the end. Note that both start and end values are included in the result.

In [11]:
# Slicing only based on rows

df.loc[0:5]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom

In [12]:
# Slicing based on columns, maintaining all rows. Note that : means all 

df.loc[:, ["InvoiceNo", "Description"]]

       InvoiceNo                          Description
0         536365   WHITE HANGING HEART T-LIGHT HOLDER
1         536365                  WHITE METAL LANTERN
2         536365       CREAM CUPID HEARTS COAT HANGER
3         536365  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365       RED WOOLLY HOTTIE WHITE HEART.
...          ...                                  ...
541904    581587          PACK OF 20 SPACEBOY NAPKINS
541905    581587         CHILDREN'S APRON DOLLY GIRL
541906    581587        CHILDRENS CUTLERY DOLLY GIRL
541907    581587      CHILDRENS CUTLERY CIRCUS PARADE
541908    581587        BAKING SET 9 PIECE RETROSPOT

[541909 rows x 2 columns]

Note how the desired columns are given as a list if there are multiple.

In [13]:
# When returning only one column the column name does not have to be given as a list

df.loc[:, "Description"]

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541904            PACK OF 20 SPACEBOY NAPKINS
541905           CHILDREN'S APRON DOLLY GIRL
541906          CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908          BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 541909, dtype: object

In [14]:
# Specifying both rows and columns, wanting the unit price and quantity for rows 5-7

df.loc[5:7, ["UnitPrice", "Quantity"]]

   UnitPrice  Quantity
5       7.65         2
6       4.25         6
7       1.85         6

### Boolean example

We want to get a subset of the dataset with rows where the UnitPrice is above 10. Here is one approach to doing it.

In [15]:
# Getting the boolean array

expensive = df["UnitPrice"] > 10

expensive

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: UnitPrice, Length: 541909, dtype: bool

In [16]:
# Subsetting the dataset with this boolean array

df[expensive]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.00,12583.0,France
65,536374,21258,VICTORIAN SEWING BOX LARGE,32,2010-12-01 09:09:00,10.95,15100.0,United Kingdom
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
151,536382,22839,3 TIER CAKE TIN GREEN AND CREAM,2,2010-12-01 09:45:00,14.95,16098.0,United Kingdom
152,536382,22838,3 TIER CAKE TIN RED AND CREAM,2,2010-12-01 09:45:00,14.95,16098.0,United Kingdom
...,...,...,...,...,...,...,...,...
541762,581574,21258,VICTORIAN SEWING BOX LARGE,2,2011-12-09 12:09:00,12.75,12526.0,Germany
541763,581574,23111,PARISIENNE SEWING BOX,2,2011-12-09 12:09:00,12.50,12526.0,Germany
541767,581574,POST,POSTAGE,2,2011-12-09 12:09:00,18.00,12526.0,Germany
541768,581578,POST,POSTAGE,3,2011-12-09 12:16:00,18.00,12713.0,Germany
541786,581578,22622,BOX OF VINTAGE ALPHABET BLOCKS,6,2011-12-09 12:16:00,11.95,12713.0,Germany

In [17]:
# Note that this could done with just one row

df[df["UnitPrice"] > 10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.00,12583.0,France
65,536374,21258,VICTORIAN SEWING BOX LARGE,32,2010-12-01 09:09:00,10.95,15100.0,United Kingdom
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
151,536382,22839,3 TIER CAKE TIN GREEN AND CREAM,2,2010-12-01 09:45:00,14.95,16098.0,United Kingdom
152,536382,22838,3 TIER CAKE TIN RED AND CREAM,2,2010-12-01 09:45:00,14.95,16098.0,United Kingdom
...,...,...,...,...,...,...,...,...
541762,581574,21258,VICTORIAN SEWING BOX LARGE,2,2011-12-09 12:09:00,12.75,12526.0,Germany
541763,581574,23111,PARISIENNE SEWING BOX,2,2011-12-09 12:09:00,12.50,12526.0,Germany
541767,581574,POST,POSTAGE,2,2011-12-09 12:09:00,18.00,12526.0,Germany
541768,581578,POST,POSTAGE,3,2011-12-09 12:16:00,18.00,12713.0,Germany
541786,581578,22622,BOX OF VINTAGE ALPHABET BLOCKS,6,2011-12-09 12:16:00,11.95,12713.0,Germany

Elegant? No. But it does what it is supposed to do.

## Using .iloc

### Selecting rows and returning a Pandas series or DataFrame

In [18]:
# Single bracket returns an array

df.loc[1]

InvoiceNo                   536365
StockCode                    71053
Description    WHITE METAL LANTERN
Quantity                         6
InvoiceDate    2010-12-01 08:26:00
UnitPrice                     3.39
CustomerID                 17850.0
Country             United Kingdom
Name: 1, dtype: object

In [19]:
# Double bracket returns a DataFrame

df.iloc[[1]]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [20]:
# Notice the difference when comparing .loc and iloc. The slice returns only the five first positions. 
# With .loc it would return six rows, while iloc returns five. 

df.iloc[0:5]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [21]:
# Slicing based on column positions, maintaining all rows.


df.iloc[:, 0:2]

       InvoiceNo StockCode
0         536365    85123A
1         536365     71053
2         536365    84406B
3         536365    84029G
4         536365    84029E
...          ...       ...
541904    581587     22613
541905    581587     22899
541906    581587     23254
541907    581587     23255
541908    581587     22138

[541909 rows x 2 columns]

## Selecting data without .iloc and .loc

In [22]:
# Selecting rows

df[0:5]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [23]:
# Selecting a column

df["Description"]

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541904            PACK OF 20 SPACEBOY NAPKINS
541905           CHILDREN'S APRON DOLLY GIRL
541906          CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908          BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 541909, dtype: object

In [24]:
# Selecting multiple columns

df[["Description", "Country"]]

                                Description         Country
0        WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
1                       WHITE METAL LANTERN  United Kingdom
2            CREAM CUPID HEARTS COAT HANGER  United Kingdom
3       KNITTED UNION FLAG HOT WATER BOTTLE  United Kingdom
4            RED WOOLLY HOTTIE WHITE HEART.  United Kingdom
...                                     ...             ...
541904          PACK OF 20 SPACEBOY NAPKINS          France
541905         CHILDREN'S APRON DOLLY GIRL           France
541906        CHILDRENS CUTLERY DOLLY GIRL           France
541907      CHILDRENS CUTLERY CIRCUS PARADE          France
541908        BAKING SET 9 PIECE RETROSPOT           France

[541909 rows x 2 columns]

In [25]:
# Selecting rows and columns

df[0:5][["Description", "Country"]]

                           Description         Country
0   WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
1                  WHITE METAL LANTERN  United Kingdom
2       CREAM CUPID HEARTS COAT HANGER  United Kingdom
3  KNITTED UNION FLAG HOT WATER BOTTLE  United Kingdom
4       RED WOOLLY HOTTIE WHITE HEART.  United Kingdom

## A note on subsetting DataFrames

In [26]:
# Let's take a subset of the first five rows and store it

first_five = df[0:5]

first_five

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [27]:
# Let's change the country to "Narnia" in this subset

first_five.loc[0:5, "Country"] = "Narnia"

first_five

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Narnia
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Narnia
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,Narnia

In [28]:
# Now let's look at our original dataset

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Narnia
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Narnia
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

Oh no! Looks like we inadvertently changed the original dataset. How did this happen? Because both were in fact referring to the same object. The first_five did not create a copy of the first five rows, but rather referenced the five rows inside the object df.

In [33]:
# Restoring the original df

df = pd.read_excel("Online Retail.xlsx")

Now we have the dataframe in its original form. This would be a pain if the dataset was massive and took long to load...

How can we avoid this issue?

In [34]:
# Use the .copy() method of pandas to make a true copy rather than referencing the same object

first_five = df.copy()[0:5]

In [35]:
first_five.loc[0:5, "Country"] = "Narnia"

In [36]:
first_five.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,Narnia
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,Narnia
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,Narnia
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,Narnia

In [37]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom