# Week 2 exercises: NumPy, Pandas, and Modules — SOLUTIONS

*Solution notebook. For the best learning experience, do not open this before having attempted and ideally solved the exercise se on your own!*

---

## Part 1: Modules, Packages and Libraries

### Exercise 1: Importing Modules

a) Import the `math` module and use it to compute the square root of 144 and the value of $e^2$. Print both results.

b) Import only the `ceil` and `floor` functions from the `math` module. Apply both to the value `7.3` and print the results.

c) Import the `random` module with the alias `rng`. Use `rng.randint(1, 100)` to generate and print a random integer between 1 and 100.

In [26]:
# a) Import math and compute sqrt(144) and e^2

import math

print(math.sqrt(144))
print(math.exp(2))

12.0
7.38905609893065

In [27]:
# b) Import only ceil and floor from math

from math import ceil, floor

print(ceil(7.3))
print(floor(7.3))

8
7

In [28]:
# c) Import random with alias rng

import random as rng

print(rng.randint(1, 100)) # Since we did not set a seed, this will be different every time

27

### Exercise 2: Exploring the Standard Library

a) Import the `datetime` module. Create a variable `today` that stores today's date using `datetime.date.today()`. Print the result.

b) Import the `os` module and use `os.getcwd()` to print your current working directory.

In [30]:
# a) Import datetime and get today's date

import datetime

today = datetime.date.today()
print(today)

2026-03-27

In [31]:
# b) Import os and print current working directory

import os

print(os.getcwd())

/Users/sippo/PythonForBusinessInt2026/exercises

## Part 2: NumPy

### Exercise 3: Creating and Inspecting Arrays

a) Import NumPy as `np`. Create a 1D array called `revenues` containing the values: `[120, 95, 200, 180, 160, 210, 190]`. These represent daily revenues in thousands of euros for a week.

b) Print the array's `ndim`, `shape`, `size`, and `dtype`.

c) Create a 2D array with shape `(3, 4)` containing integers from 1 to 12 using `np.arange()` and `.reshape()`. Print the array.

In [33]:
# a) Import NumPy and create the revenues array
import numpy as np

revenues = np.array([120, 95, 200, 180, 160, 210, 190])
revenues

array([120,  95, 200, 180, 160, 210, 190])

In [36]:
# b) Print array attributes

print("ndim:", revenues.ndim)
print("shape:", revenues.shape)
print("size:", revenues.size)
print("dtype:", revenues.dtype)

ndim: 1
shape: (7,)
size: 7
dtype: int64

In [37]:
# c) Create a 2D array with shape (3, 4)

array_2d = np.arange(1, 13).reshape((3, 4))
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

### Exercise 4: Array Slicing

Using the `revenues` array:

a) Print the first three elements.

b) Print every other element starting from index 1.

c) Print the array in reversed order.

d) Using the 2D `data` array from Exercise 3c, extract and print:
- The first two rows and first two columns.
- The entire last column.

In [44]:
# revenues = np.array([120, 95, 200, 180, 160, 210, 190])

# a) First three elements

print(revenues[:3])

[120  95 200]

In [45]:
# b) Every other element starting from index 1

print(revenues[1::2])

[ 95 180 210]

In [46]:
# c) Reversed order

print(revenues[::-1])

[190 210 160 180 200  95 120]

In [47]:
# d) 2D slicing using the array from Exercise 3c
# array_2d = np.arange(1, 13).reshape((3, 4))

# First two rows and first two columns
print(array_2d[:2, :2])

# Entire last column
print(array_2d[:, -1])

[[1 2]
 [5 6]]
[ 4  8 12]

## Part 3: Pandas — Series and DataFrames

### Exercise 5: Creating a DataFrame

a) Create a DataFrame called `products` from the following dictionary:

```python
product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}
```

b) Print the DataFrame's `index` and `columns`.

c) Add a new column called `revenue` that is the product of `price` and `units_sold`.

d) Print the resulting DataFrame.

In [51]:
import pandas as pd

# a) Create the DataFrame

product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}

products = pd.DataFrame(product_data)
products # This prints just out the dataframe nicely. This only works if it is the last item in a cell.

   product  price  units_sold
0   Laptop   1200         150
1    Phone    800         300
2   Tablet    450         200
3  Monitor    350         100

In [52]:
# b) Print index and columns

print(products.index)
print(products.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['product', 'price', 'units_sold'], dtype='object')

In [61]:
# c) Add revenue column

products["revenue"] = products["price"] * products["units_sold"]

In [62]:
# d) Print the DataFrame

print(products)  # Note the difference between using print(products) vs products

   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000

In [63]:
products

   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000

### Exercise 6: Creating DataFrames from Other Sources

a) Create a DataFrame from a list of dictionaries:

```python
employees = [
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
]
```

b) Create a DataFrame from a 2D NumPy array of shape `(3, 2)` with random values. Assign column names `"A"` and `"B"` and index labels `"x"`, `"y"`, `"z"`.

c) Print both DataFrames.

In [73]:
# a) DataFrame from a list of dictionaries

employees = [
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
]

df_employees = pd.DataFrame(employees)

In [74]:
# b) DataFrame from a 2D NumPy array

df_array = pd.DataFrame(
    np.random.rand(3, 2),
    columns=["A", "B"],
    index=["x", "y", "z"]
)

In [75]:
# c) Print both

print(df_employees)
print()              # This is just to make the dataframes print with an empty row between them
print(df_array)

   name department  salary
0  Anna    Finance    4500
1  Erik  Marketing    4000
2   Mia    Finance    4800

          A         B
x  0.609318  0.889653
y  0.528800  0.289290
z  0.793415  0.660073

## Part 4: Pandas — Subsetting and Slicing

### Exercise 7: Selecting with `.loc`

Use the `products` DataFrame from Exercise 5 for this exercise.

a) Select and print the row at index `1` using `.loc`. What type is the result?

b) Select and print the row at index `1` using `.loc` with double brackets. What type is the result now?

c) Select and print only the `product` and `price` columns for all rows using `.loc`.

d) Select and print the `price` and `units_sold` columns for rows 1 to 2 (inclusive) using `.loc`.

In [81]:
# a) Single bracket .loc returns a Series

print(products.loc[1])
print(type(products.loc[1]))

product        Phone
price            800
units_sold       300
revenue       240000
Name: 1, dtype: object
<class 'pandas.core.series.Series'>

In [82]:
# b) Double bracket .loc returns a DataFrame

print(products.loc[[1]])
print(type(products.loc[[1]]))

  product  price  units_sold  revenue
1   Phone    800         300   240000
<class 'pandas.core.frame.DataFrame'>

In [83]:
# c) Select product and price columns for all rows

print(products.loc[:, ["product", "price"]])

   product  price
0   Laptop   1200
1    Phone    800
2   Tablet    450
3  Monitor    350

In [84]:
# d) Select price and units_sold for rows 1 to 2 (inclusive)

print(products.loc[1:2, ["price", "units_sold"]])

   price  units_sold
1    800         300
2    450         200

### Exercise 8: Selecting with `.iloc`

Using the same `products` DataFrame:

a) Select the first two rows using `.iloc`.

b) Select the element in the third row, second column using `.iloc`.

c) Select all rows but only the first and third columns using `.iloc`.

d) What is the difference between `df.loc[0:2]` and `df.iloc[0:2]`? Test both and explain in a comment.

In [85]:
# a) First two rows

print(products.iloc[0:2])

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000

In [87]:
# b) Element in third row, second column

print(products.iloc[2, 1])

450

In [88]:
# c) All rows, first and third columns

print(products.iloc[:, [0, 2]])

   product  units_sold
0   Laptop         150
1    Phone         300
2   Tablet         200
3  Monitor         100

In [90]:
# d) Difference between .loc[0:2] and .iloc[0:2]

print(products.loc[0:2])   # Returns rows with labels 0, 1, 2 (inclusive)
print()
print(products.iloc[0:2])  # Returns rows at positions 0, 1 (exclusive upper bound)

# .loc uses label-based indexing where the endpoint is inclusive.
# .iloc uses position-based indexing where the endpoint is exclusive,
# just like standard Python slicing.

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000
2  Tablet    450         200    90000

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000

### Exercise 9: Boolean Indexing

Using the `products` DataFrame:

a) Create a boolean mask that identifies products with a price above 500€. Print the mask.

b) Use the mask to subset the DataFrame and print only the expensive products.

c) In a single line, select all products where `units_sold` is greater than or equal to 200. Print the result.

In [91]:
# a) Boolean mask for price above 500

expensive_mask = products["price"] > 500
print(expensive_mask)

0     True
1     True
2    False
3    False
Name: price, dtype: bool

In [92]:
# b) Subset using the mask

print(products[expensive_mask])

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000

In [93]:
# c) Single-line boolean indexing

print(products[products["units_sold"] >= 200])

  product  price  units_sold  revenue
1   Phone    800         300   240000
2  Tablet    450         200    90000

### Exercise 10: Putting It All Together

A small shop tracks weekly sales in a dictionary:

```python
sales_data = {
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "customers": [30, 45, 50, 35, 60, 80, 70],
    "sales_eur": [600, 900, 1100, 750, 1300, 1800, 1500]
}
```

a) Create a DataFrame from this dictionary.

b) Add a column `avg_spend` that computes the average spending per customer (i.e., `sales_eur / customers`).

c) Using boolean indexing, filter the DataFrame to show only days where the number of customers exceeded 50.

d) Using `.iloc`, select the data for the weekend (last two rows) and all columns except `day`.

e) What was the total revenue for the week? Use NumPy or Pandas to compute and print the answer.

In [95]:
# a) Create the DataFrame

sales_data = {
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "customers": [30, 45, 50, 35, 60, 80, 70],
    "sales_eur": [600, 900, 1100, 750, 1300, 1800, 1500]
}

sales = pd.DataFrame(sales_data)
sales

   day  customers  sales_eur
0  Mon         30        600
1  Tue         45        900
2  Wed         50       1100
3  Thu         35        750
4  Fri         60       1300
5  Sat         80       1800
6  Sun         70       1500

In [96]:
# b) Add avg_spend column

sales["avg_spend"] = sales["sales_eur"] / sales["customers"]

In [97]:
# c) Filter days where customers exceeded 50

print(sales[sales["customers"] > 50])

   day  customers  sales_eur  avg_spend
4  Fri         60       1300  21.666667
5  Sat         80       1800  22.500000
6  Sun         70       1500  21.428571

In [99]:
# d) Weekend data (last two rows), all columns except day

print(sales.iloc[-2:, 1:])

   customers  sales_eur  avg_spend
5         80       1800  22.500000
6         70       1500  21.428571

In [100]:
# e) Total revenue for the week

print(f"Total weekly revenue: {sales['sales_eur'].sum()}€")

Total weekly revenue: 7950€